In [1]:
import pandas as pd
import nibabel as nib
import numpy as np
from skimage import measure
import json
import os
join = os.path.join

In [9]:
a = {'a':1, 'b':2}
for key, value in a.items():
    a[key] = value + 1
a.keys()

dict_keys(['a', 'b'])

In [8]:
root = "/homes/syli/dataset/EC_all/EC_114_spacing"
df = pd.read_csv("/homes/syli/dataset/LVSI_LNM/train_clinical_feature.csv")
casenames = df["CaseName"].tolist()
labels = df[["LVSI", "LNM"]].values.tolist()
caselist = []
for i, j in zip(casenames, labels):
    casedict = {"DWI": join(root, i, f"DWI_resampled.nii"),
                 "T1CE": join(root, i, f"T1CE_resampled.nii"),
                   "T2": join(root, i, f"T2_resampled.nii"), "label": j,
                   "DWI_roi": join(root, i, f"DWI_roi_resampled.nii.gz"),
                   "T1CE_roi": join(root, i, f"T1CE_roi_resampled.nii.gz"),
                   "T2_roi": join(root, i, f"T2_roi_resampled.nii.gz")}
    caselist.append(casedict)
a = dict()
a["train"] = caselist
df = pd.read_csv("/homes/syli/dataset/LVSI_LNM/test_clinical_feature.csv")
casenames = df["CaseName"].tolist()
labels = df[["LVSI", "LNM"]].values.tolist()
caselist = []
for i, j in zip(casenames, labels):
    casedict = {"DWI": join(root, i, f"DWI_resampled.nii"),
                 "T1CE": join(root, i, f"T1CE_resampled.nii"),
                   "T2": join(root, i, f"T2_resampled.nii"), "label": j,
                   "DWI_roi": join(root, i, f"DWI_roi_resampled.nii.gz"),
                   "T1CE_roi": join(root, i, f"T1CE_roi_resampled.nii.gz"),
                   "T2_roi": join(root, i, f"T2_roi_resampled.nii.gz")}
    caselist.append(casedict)
a["validation"] = caselist
with open("/homes/syli/dataset/LVSI_LNM/dataset.json", "w") as f:
    json.dump(a, f)

In [7]:
root = "/homes/syli/dataset/EC_all/EC_114_spacing"
df = pd.read_csv("/homes/syli/dataset/LVSI_LNM/test_clinical_feature.csv")
casenames = df["CaseName"].tolist()
for modal in ["T1CE", "T2", "DWI"]:
    shapes = []
    for i in casenames:
        img = nib.load(join(root, i, f"{modal}_roi_resampled.nii.gz"))
        img_data = img.get_fdata()
        bbox = measure.regionprops(measure.label(img_data))[0].bbox
        
        shapes.append(img_data.shape)
    shapes = np.array(shapes)
    
    print(np.min(shapes, axis=0))

[210 250  16]
[250 250  20]
[221 221  12]
